#!/bin/bash
# Fresh Postgres volume only — existing volumes use ensure_app_db_role at backend boot.
set -euo pipefail

APP_ROLE="${POSTGRES_APP_USER:-agent_saas_app}"
APP_PASSWORD="${POSTGRES_APP_PASSWORD:-$POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN
    CREATE ROLE ${APP_ROLE} LOGIN PASSWORD '${APP_PASSWORD}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
  ELSE
    ALTER ROLE ${APP_ROLE} WITH LOGIN PASSWORD '${APP_PASSWORD}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
  END IF;
END
\$\$;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_ROLE};
GRANT USAGE, CREATE ON SCHEMA public TO ${APP_ROLE};
CREATE SCHEMA IF NOT EXISTS ai;
ALTER SCHEMA ai OWNER TO ${APP_ROLE};
GRANT USAGE, CREATE ON SCHEMA ai TO ${APP_ROLE};
EOSQL
