from __future__ import annotations

import importlib
from dataclasses import asdict, dataclass, field
from functools import cache
from typing import Any, Literal

SafetyTier = Literal["safe", "credential", "blocked"]


@dataclass(frozen=True, slots=True)
class CredentialSpec:
    env_var: str
    provider: str
    kwarg: str = "api_key"


@dataclass(frozen=True, slots=True)
class ToolkitSpec:
    key: str
    label: str
    category: str
    description: str
    module: str
    class_name: str
    tier: SafetyTier
    credentials: tuple[CredentialSpec, ...] = ()
    options: dict[str, dict[str, Any]] = field(default_factory=dict)
    side_effects: bool = False
    install_hint: str | None = None
    disabled_reason: str | None = None
    exposed: bool = True


def _credential(
    key: str,
    label: str,
    category: str,
    module: str,
    class_name: str,
    provider: str,
    env_var: str,
    *,
    kwarg: str = "api_key",
    description: str | None = None,
    side_effects: bool = False,
    hint: str | None = None,
    disabled: str | None = None,
) -> ToolkitSpec:
    return ToolkitSpec(
        key=key,
        label=label,
        category=category,
        description=description or f"Use {label} through its server-managed Agno toolkit.",
        module=module,
        class_name=class_name,
        tier="credential",
        credentials=(CredentialSpec(env_var, provider, kwarg),),
        side_effects=side_effects,
        install_hint=hint,
        disabled_reason=disabled,
    )


def _safe(
    key: str,
    label: str,
    category: str,
    module: str,
    class_name: str,
    description: str,
    *,
    options: dict[str, dict[str, Any]] | None = None,
    hint: str | None = None,
) -> ToolkitSpec:
    return ToolkitSpec(
        key=key,
        label=label,
        category=category,
        description=description,
        module=module,
        class_name=class_name,
        tier="safe",
        options=options or {},
        install_hint=hint,
    )


SAFE_TOOLKITS = (
    _safe(
        "calculator",
        "Calculator",
        "Utilities",
        "calculator",
        "CalculatorTools",
        "Arithmetic and number utilities.",
    ),
    _safe(
        "web_search",
        "Web Search (DDGS)",
        "Search",
        "websearch",
        "WebSearchTools",
        "Public web and news search with bounded results.",
        options={
            "max_results": {
                "type": "integer",
                "minimum": 1,
                "maximum": 10,
                "default": 5,
                "kwarg": "fixed_max_results",
            }
        },
    ),
    _safe(
        "duckduckgo",
        "DuckDuckGo",
        "Search",
        "duckduckgo",
        "DuckDuckGoTools",
        "Search the public web and news.",
        hint="pip install ddgs",
    ),
    _safe(
        "wikipedia",
        "Wikipedia",
        "Research",
        "wikipedia",
        "WikipediaTools",
        "Search and read Wikipedia.",
        hint="pip install wikipedia",
    ),
    _safe(
        "arxiv",
        "arXiv",
        "Research",
        "arxiv",
        "ArxivTools",
        "Search open-access research papers.",
        hint="pip install arxiv",
    ),
    _safe(
        "hackernews",
        "Hacker News",
        "Research",
        "hackernews",
        "HackerNewsTools",
        "Read top stories and public user details.",
    ),
    _safe(
        "pubmed",
        "PubMed",
        "Research",
        "pubmed",
        "PubmedTools",
        "Search biomedical literature.",
        options={"max_results": {"type": "integer", "minimum": 1, "maximum": 20, "default": 5}},
    ),
    _safe(
        "yfinance",
        "Yahoo Finance",
        "Finance",
        "yfinance",
        "YFinanceTools",
        "Read public market data.",
        hint="pip install yfinance",
    ),
    _safe(
        "website",
        "Website Reader",
        "Content",
        "website",
        "WebsiteTools",
        "Read public website content.",
    ),
    _safe(
        "newspaper",
        "Newspaper",
        "Content",
        "newspaper",
        "NewspaperTools",
        "Extract article text and metadata.",
        hint="pip install newspaper3k lxml_html_clean",
    ),
    _safe(
        "newspaper4k",
        "Newspaper4k",
        "Content",
        "newspaper4k",
        "Newspaper4kTools",
        "Extract article text and metadata.",
        hint="pip install newspaper4k lxml_html_clean",
    ),
    _safe(
        "trafilatura",
        "Trafilatura",
        "Content",
        "trafilatura",
        "TrafilaturaTools",
        "Extract readable web content.",
        hint="pip install trafilatura",
    ),
    _safe(
        "youtube",
        "YouTube Transcript",
        "Content",
        "youtube",
        "YouTubeTools",
        "Read public video transcripts.",
        hint="pip install youtube-transcript-api",
    ),
    _safe(
        "llms_txt",
        "llms.txt",
        "Content",
        "llms_txt",
        "LlmTxtTools",
        "Read public llms.txt documentation.",
        hint="pip install requests",
    ),
    _safe(
        "baidusearch",
        "Baidu Search",
        "Search",
        "baidusearch",
        "BaiduSearchTools",
        "Search the public web through Baidu.",
        hint="pip install baidusearch",
    ),
    _safe(
        "webtools",
        "Web Utilities",
        "Content",
        "webtools",
        "WebTools",
        "Expand and inspect public URLs.",
    ),
)


CREDENTIAL_TOOLKITS = (
    _credential(
        "openai_media",
        "OpenAI Media",
        "AI media",
        "openai",
        "OpenAITools",
        "openai",
        "OPENAI_API_KEY",
        side_effects=True,
    ),
    _credential(
        "nano_banana",
        "Nano Banana",
        "AI media",
        "nano_banana",
        "NanoBananaTools",
        "google",
        "GOOGLE_API_KEY",
        side_effects=True,
        hint="pip install google-genai",
    ),
    _credential(
        "desi_vocal",
        "Desi Vocal",
        "AI media",
        "desi_vocal",
        "DesiVocalTools",
        "desi_vocal",
        "DESI_VOCAL_API_KEY",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "scavio",
        "Scavio",
        "AI media",
        "scavio",
        "ScavioTools",
        "scavio",
        "SCAVIO_API_KEY",
        side_effects=True,
        hint="pip install scavio",
    ),
    _credential(
        "seltz",
        "Seltz",
        "Web & scraping",
        "seltz",
        "SeltzTools",
        "seltz",
        "SELTZ_API_KEY",
        side_effects=True,
        hint="pip install seltz",
    ),
    _credential(
        "sofya",
        "Sofya",
        "Web & scraping",
        "sofya",
        "SofyaTools",
        "sofya",
        "SOFYA_API_KEY",
        hint="pip install requests",
    ),
    _credential(
        "superserve",
        "Superserve",
        "Business",
        "superserve",
        "SuperserveTools",
        "superserve",
        "SUPERSERVE_API_KEY",
        side_effects=True,
        hint="pip install superserve",
    ),
    _credential(
        "email",
        "SMTP Email",
        "Communication",
        "email",
        "EmailTools",
        "email",
        "EMAIL_PASSKEY",
        kwarg="sender_passkey",
        side_effects=True,
        disabled="Sender and receiver configuration requires multi-value credentials.",
    ),
    _credential(
        "tavily",
        "Tavily",
        "Search",
        "tavily",
        "TavilyTools",
        "tavily",
        "TAVILY_API_KEY",
        hint="pip install tavily-python",
    ),
    _credential(
        "exa", "Exa", "Search", "exa", "ExaTools", "exa", "EXA_API_KEY", hint="pip install exa-py"
    ),
    _credential(
        "serpapi",
        "SerpAPI",
        "Search",
        "serpapi",
        "SerpApiTools",
        "serpapi",
        "SERPAPI_API_KEY",
        hint="pip install google-search-results",
    ),
    _credential(
        "serper",
        "Serper",
        "Search",
        "serper",
        "SerperTools",
        "serper",
        "SERPER_API_KEY",
        hint="pip install requests",
    ),
    _credential(
        "searchapi",
        "SearchApi",
        "Search",
        "searchapi",
        "SearchApiTools",
        "searchapi",
        "SEARCHAPI_API_KEY",
        hint="pip install requests",
    ),
    _credential(
        "linkup",
        "Linkup",
        "Search",
        "linkup",
        "LinkupTools",
        "linkup",
        "LINKUP_API_KEY",
        hint="pip install linkup-sdk",
    ),
    _credential(
        "bravesearch",
        "Brave Search",
        "Search",
        "bravesearch",
        "BraveSearchTools",
        "brave",
        "BRAVE_API_KEY",
    ),
    _credential("youcom", "You.com", "Search", "youcom", "YouComTools", "youcom", "YOUCOM_API_KEY"),
    _credential(
        "perplexity",
        "Perplexity",
        "Search",
        "perplexity",
        "PerplexityTools",
        "perplexity",
        "PERPLEXITY_API_KEY",
    ),
    _credential(
        "parallel",
        "Parallel",
        "Search",
        "parallel",
        "ParallelTools",
        "parallel",
        "PARALLEL_API_KEY",
    ),
    _credential("valyu", "Valyu", "Search", "valyu", "ValyuTools", "valyu", "VALYU_API_KEY"),
    _credential("jina", "Jina Reader", "Search", "jina", "JinaReaderTools", "jina", "JINA_API_KEY"),
    _credential(
        "firecrawl",
        "Firecrawl",
        "Web & scraping",
        "firecrawl",
        "FirecrawlTools",
        "firecrawl",
        "FIRECRAWL_API_KEY",
        hint="pip install firecrawl-py",
    ),
    _credential(
        "crawl4ai",
        "Crawl4AI Cloud",
        "Web & scraping",
        "crawl4ai",
        "Crawl4aiTools",
        "crawl4ai",
        "CRAWL4AI_API_KEY",
    ),
    _credential(
        "apify",
        "Apify",
        "Web & scraping",
        "apify",
        "ApifyTools",
        "apify",
        "APIFY_API_TOKEN",
        kwarg="api_token",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "agentql",
        "AgentQL",
        "Web & scraping",
        "agentql",
        "AgentQLTools",
        "agentql",
        "AGENTQL_API_KEY",
    ),
    _credential(
        "browserbase",
        "Browserbase",
        "Web & scraping",
        "browserbase",
        "BrowserbaseTools",
        "browserbase",
        "BROWSERBASE_API_KEY",
        side_effects=True,
    ),
    _credential(
        "brightdata",
        "Bright Data",
        "Web & scraping",
        "brightdata",
        "BrightDataTools",
        "brightdata",
        "BRIGHT_DATA_API_KEY",
    ),
    _credential(
        "oxylabs",
        "Oxylabs",
        "Web & scraping",
        "oxylabs",
        "OxylabsTools",
        "oxylabs",
        "OXYLABS_PASSWORD",
        kwarg="password",
    ),
    _credential(
        "scrapegraph",
        "ScrapeGraph",
        "Web & scraping",
        "scrapegraph",
        "ScrapeGraphTools",
        "scrapegraph",
        "SGAI_API_KEY",
    ),
    _credential(
        "spider", "Spider", "Web & scraping", "spider", "SpiderTools", "spider", "SPIDER_API_KEY"
    ),
    _credential(
        "github",
        "GitHub",
        "Engineering",
        "github",
        "GithubTools",
        "github",
        "GITHUB_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
        hint="pip install pygithub",
    ),
    _credential(
        "gitlab",
        "GitLab",
        "Engineering",
        "gitlab",
        "GitLabTools",
        "gitlab",
        "GITLAB_TOKEN",
        kwarg="private_token",
        side_effects=True,
        hint="pip install python-gitlab",
    ),
    _credential(
        "bitbucket",
        "Bitbucket",
        "Engineering",
        "bitbucket",
        "BitbucketTools",
        "bitbucket",
        "BITBUCKET_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "jira",
        "Jira",
        "Productivity",
        "jira",
        "JiraTools",
        "jira",
        "JIRA_API_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install jira",
    ),
    _credential(
        "linear",
        "Linear",
        "Productivity",
        "linear",
        "LinearTools",
        "linear",
        "LINEAR_API_KEY",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "confluence",
        "Confluence",
        "Productivity",
        "confluence",
        "ConfluenceTools",
        "confluence",
        "CONFLUENCE_API_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "notion",
        "Notion",
        "Productivity",
        "notion",
        "NotionTools",
        "notion",
        "NOTION_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install notion-client",
    ),
    _credential(
        "trello",
        "Trello",
        "Productivity",
        "trello",
        "TrelloTools",
        "trello",
        "TRELLO_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install py-trello",
    ),
    _credential(
        "clickup",
        "ClickUp",
        "Productivity",
        "clickup",
        "ClickUpTools",
        "clickup",
        "CLICKUP_API_KEY",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "todoist",
        "Todoist",
        "Productivity",
        "todoist",
        "TodoistTools",
        "todoist",
        "TODOIST_API_TOKEN",
        kwarg="api_token",
        side_effects=True,
        hint="pip install todoist-api-python",
    ),
    _credential(
        "calcom",
        "Cal.com",
        "Productivity",
        "calcom",
        "CalComTools",
        "calcom",
        "CALCOM_API_KEY",
        side_effects=True,
    ),
    _credential(
        "slack",
        "Slack",
        "Communication",
        "slack",
        "SlackTools",
        "slack",
        "SLACK_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install slack-sdk",
    ),
    _credential(
        "discord",
        "Discord",
        "Communication",
        "discord",
        "DiscordTools",
        "discord",
        "DISCORD_BOT_TOKEN",
        kwarg="bot_token",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "telegram",
        "Telegram",
        "Communication",
        "telegram",
        "TelegramTools",
        "telegram",
        "TELEGRAM_BOT_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install pyTelegramBotAPI",
    ),
    _credential(
        "resend",
        "Resend",
        "Communication",
        "resend",
        "ResendTools",
        "resend",
        "RESEND_API_KEY",
        side_effects=True,
        hint="pip install resend",
    ),
    _credential(
        "plivo",
        "Plivo",
        "Communication",
        "plivo",
        "PlivoTools",
        "plivo",
        "PLIVO_AUTH_TOKEN",
        kwarg="auth_token",
        side_effects=True,
    ),
    _credential(
        "twilio",
        "Twilio",
        "Communication",
        "twilio",
        "TwilioTools",
        "twilio",
        "TWILIO_AUTH_TOKEN",
        kwarg="auth_token",
        side_effects=True,
    ),
    _credential(
        "webex",
        "Webex",
        "Communication",
        "webex",
        "WebexTools",
        "webex",
        "WEBEX_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "whatsapp",
        "WhatsApp",
        "Communication",
        "whatsapp",
        "WhatsAppTools",
        "whatsapp",
        "WHATSAPP_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "zoom",
        "Zoom",
        "Communication",
        "zoom",
        "ZoomTools",
        "zoom",
        "ZOOM_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "aws_ses",
        "Amazon SES",
        "Communication",
        "aws_ses",
        "AwsSesTools",
        "aws",
        "AWS_SECRET_ACCESS_KEY",
        kwarg="secret_access_key",
        side_effects=True,
    ),
    _credential(
        "openweather",
        "OpenWeather",
        "Location",
        "openweather",
        "OpenWeatherTools",
        "openweather",
        "OPENWEATHER_API_KEY",
        hint="pip install requests",
    ),
    _credential(
        "google_maps",
        "Google Maps",
        "Location",
        "google_maps",
        "GoogleMapsTools",
        "google_maps",
        "GOOGLE_MAPS_API_KEY",
        hint="pip install googlemaps google-maps-places",
    ),
    _credential(
        "financial_datasets",
        "Financial Datasets",
        "Finance",
        "financial_datasets",
        "FinancialDatasetsTools",
        "financial_datasets",
        "FINANCIAL_DATASETS_API_KEY",
        hint="pip install requests",
    ),
    _credential("openbb", "OpenBB", "Finance", "openbb", "OpenBBTools", "openbb", "OPENBB_API_KEY"),
    _credential(
        "salesforce",
        "Salesforce",
        "Business",
        "salesforce",
        "SalesforceTools",
        "salesforce",
        "SALESFORCE_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
        hint="pip install simple-salesforce",
    ),
    _credential(
        "shopify",
        "Shopify",
        "Business",
        "shopify",
        "ShopifyTools",
        "shopify",
        "SHOPIFY_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "zendesk",
        "Zendesk",
        "Business",
        "zendesk",
        "ZendeskTools",
        "zendesk",
        "ZENDESK_API_TOKEN",
        kwarg="token",
        side_effects=True,
        hint="pip install requests",
    ),
    _credential(
        "redmine",
        "Redmine",
        "Business",
        "redmine",
        "RedmineTools",
        "redmine",
        "REDMINE_API_KEY",
        side_effects=True,
    ),
    _credential(
        "reddit",
        "Reddit",
        "Social & media",
        "reddit",
        "RedditTools",
        "reddit",
        "REDDIT_CLIENT_SECRET",
        kwarg="client_secret",
        hint="pip install praw",
        disabled="Reddit also requires a client ID; multi-value credentials are coming soon.",
    ),
    _credential(
        "spotify",
        "Spotify",
        "Social & media",
        "spotify",
        "SpotifyTools",
        "spotify",
        "SPOTIFY_ACCESS_TOKEN",
        kwarg="access_token",
        side_effects=True,
    ),
    _credential(
        "unsplash",
        "Unsplash",
        "Social & media",
        "unsplash",
        "UnsplashTools",
        "unsplash",
        "UNSPLASH_ACCESS_KEY",
        kwarg="access_key",
    ),
    _credential(
        "giphy", "Giphy", "Social & media", "giphy", "GiphyTools", "giphy", "GIPHY_API_KEY"
    ),
    _credential(
        "x",
        "X / Twitter",
        "Social & media",
        "x",
        "XTools",
        "x",
        "X_BEARER_TOKEN",
        kwarg="bearer_token",
        side_effects=True,
        hint="pip install tweepy",
    ),
    _credential(
        "eleven_labs",
        "ElevenLabs",
        "AI media",
        "eleven_labs",
        "ElevenLabsTools",
        "elevenlabs",
        "ELEVEN_LABS_API_KEY",
        side_effects=True,
        hint="pip install elevenlabs",
    ),
    _credential(
        "dalle",
        "DALL·E",
        "AI media",
        "dalle",
        "DalleTools",
        "openai",
        "OPENAI_API_KEY",
        side_effects=True,
    ),
    _credential(
        "replicate",
        "Replicate",
        "AI media",
        "replicate",
        "ReplicateTools",
        "replicate",
        "REPLICATE_API_TOKEN",
        kwarg="api_token",
        side_effects=True,
        hint="pip install replicate",
    ),
    _credential(
        "fal",
        "fal.ai",
        "AI media",
        "fal",
        "FalTools",
        "fal",
        "FAL_KEY",
        kwarg="api_key",
        side_effects=True,
        hint="pip install fal-client",
    ),
    _credential(
        "cartesia",
        "Cartesia",
        "AI media",
        "cartesia",
        "CartesiaTools",
        "cartesia",
        "CARTESIA_API_KEY",
        side_effects=True,
    ),
    _credential(
        "lumalab",
        "Luma AI",
        "AI media",
        "lumalab",
        "LumaLabTools",
        "lumalab",
        "LUMAAI_API_KEY",
        side_effects=True,
    ),
    _credential(
        "twelvelabs",
        "Twelve Labs",
        "AI media",
        "twelvelabs",
        "TwelveLabsTools",
        "twelvelabs",
        "TWELVE_LABS_API_KEY",
    ),
    _credential(
        "brandfetch",
        "Brandfetch",
        "Business",
        "brandfetch",
        "BrandfetchTools",
        "brandfetch",
        "BRANDFETCH_API_KEY",
    ),
    _credential(
        "gmail",
        "Gmail",
        "Google Workspace",
        "gmail",
        "GmailTools",
        "google_workspace",
        "GOOGLE_CREDENTIALS",
        disabled="OAuth/service-account credential bundles are not supported yet.",
    ),
    _credential(
        "google_drive",
        "Google Drive",
        "Google Workspace",
        "google_drive",
        "GoogleDriveTools",
        "google_workspace",
        "GOOGLE_CREDENTIALS",
        disabled="OAuth/service-account credential bundles are not supported yet.",
    ),
    _credential(
        "googlecalendar",
        "Google Calendar",
        "Google Workspace",
        "googlecalendar",
        "GoogleCalendarTools",
        "google_workspace",
        "GOOGLE_CREDENTIALS",
        disabled="OAuth/service-account credential bundles are not supported yet.",
    ),
    _credential(
        "googlesheets",
        "Google Sheets",
        "Google Workspace",
        "googlesheets",
        "GoogleSheetsTools",
        "google_workspace",
        "GOOGLE_CREDENTIALS",
        disabled="OAuth/service-account credential bundles are not supported yet.",
    ),
)


BLOCKED_MODULES = {
    "airflow",
    "antigravity",
    "api",
    "aws_lambda",
    "coding",
    "csv_toolkit",
    "daytona",
    "decorator",
    "docker",
    "docling",
    "duckdb",
    "e2b",
    "evm",
    "file",
    "file_generation",
    "function",
    "google",
    "google_bigquery",
    "knowledge",
    "local_file_system",
    "mcp",
    "mcp_toolbox",
    "mem0",
    "memory",
    "mlx_transcribe",
    "models",
    "models_labs",
    "moviepy_video",
    "neo4j",
    "pandas",
    "opencv",
    "postgres",
    "reasoning",
    "redshift",
    "scheduler",
    "searxng",
    "shell",
    "sleep",
    "sql",
    "streamlit",
    "studio",
    "tool_registry",
    "toolkit",
    "user_control_flow",
    "user_feedback",
    "visualization",
    "webbrowser",
    "workflow",
    "workspace",
    "zep",
}

BLOCKED_TOOLKITS = tuple(
    ToolkitSpec(
        key=module,
        label=module.replace("_", " ").title(),
        category="Blocked",
        description="Not exposed in the multi-tenant runtime.",
        module=module,
        class_name="",
        tier="blocked",
        disabled_reason="Blocked by the Atlas multi-tenant safety policy.",
        exposed=False,
    )
    for module in sorted(BLOCKED_MODULES)
)

TOOLKIT_SPECS = SAFE_TOOLKITS + CREDENTIAL_TOOLKITS + BLOCKED_TOOLKITS
TOOLKIT_BY_KEY = {item.key: item for item in TOOLKIT_SPECS}


def toolkit_availability(spec: ToolkitSpec) -> tuple[bool, str | None]:
    return _toolkit_availability(spec.key)


@cache
def _toolkit_availability(key: str) -> tuple[bool, str | None]:
    spec = TOOLKIT_BY_KEY[key]
    if spec.tier == "blocked" or spec.disabled_reason:
        return False, spec.disabled_reason
    try:
        module = importlib.import_module(f"agno.tools.{spec.module}")
        if not hasattr(module, spec.class_name):
            return False, f"Agno {spec.class_name} is not installed in this release."
        toolkit_type = getattr(module, spec.class_name)
        kwargs = {spec.credentials[0].kwarg: "atlas-availability-check"} if spec.credentials else {}
        toolkit_type(**kwargs)
    except Exception as exc:
        return False, spec.install_hint or str(exc)
    return True, None


def public_toolkit_catalog() -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for spec in TOOLKIT_SPECS:
        available, reason = toolkit_availability(spec)
        item = asdict(spec)
        item["credentials"] = [asdict(credential) for credential in spec.credentials]
        item["available"] = available
        item["unavailable_reason"] = reason
        item["status"] = (
            "blocked"
            if spec.tier == "blocked"
            else "unavailable"
            if not available
            else "needs_credential"
            if spec.credentials
            else "ready"
        )
        result.append(item)
    return result
